def countBases(string):
    Acount = 0
    Ccount = 0
    Gcount = 0
    Tcount = 0
    for i in range(0, len(string), 1):
        if string[i] == "A":
            Acount = Acount + 1
        elif string[i] == "C":
            Ccount = Ccount + 1
        elif string[i] == "G":
            Gcount = Gcount + 1
        elif string[i] == "T":
            Tcount = Tcount + 1

    return Acount, Ccount, Gcount, Tcount

#below is to test countBases
# print(countBases("CAGTACGCAAAATTACTTTTTCCACTTCTAATCCACGATGCCGCCAGGCGGACGAGACAGGCTTGAACTTACTTTTGGTTCGGTGAATCACGCATGTGTTACCCATCTTACCTGCCCCGAACTACCTGCTCTAGATCGATTCGAGTTCCGTGCGACATAAATTGCGTAAGATCTTCTGCAGGCGGCTGTAGTACCGAAGTATACAGGTTGGTATTAGAGTAGCAACGGCTGGACCCAACCGAGGCCTGACTTTTTGTGGAATTGACATGGGCGTCCATTTCTCTGTTTTAGATCACCAAAAGTCAGTTCGTTCCCCTAGCTCAGCAGCTTTTATGCCGATGACCTGACTGAGCGTGCAGACAACTTGGCCGAAGCCATATGCACATCCGATCGGGGCACCCGCAAACATGTCGATAGGTATTCGCCGACCCGAGTGGCTCCCGCCATTATGTATCGACACGTCAGTAACAAAAAGCGACGGGCAAGGCGAGCCTAGCGGCCCCTCACCGGTCTTGACCCCCGCAATTATACCGACGACCAATTGCACCTCGCCAATCGTAGAGTAACGTGTGGCCACTCACTCAGAGTTAGACCCCGTCCCGAGATGTCGGAAAACAATGCTAATAAAGATCCGCGCGACTCTCGAAGGAGCACCGGGTTACGTAATCAACAAGCGGTTAGGCTAAAGGACTTATGGCGTTCGTCATACCTAGTGCCTGAAAGTTACGATTGCGGCCATGGAGGTGTGTTATTGCCTACTAAGCGCCCGAGCACCCGATAACACGTATACACTTACGTTAACTATAGCTTTATCCACAAAAGTGGTACTAGC"))