def transcription(DNA):

    RNA = ""

    for i in range(0, len(DNA), 1):
        if DNA[i] == "T":
            RNA += "U"
        else:
            RNA += DNA[i]
    
    return RNA

#test transcription 
print(transcription(
    "CAGTCTCAAGGATATCTCCCTAGCCAGTGCCTCAGTTGCGAAGTTCACCTCACTTACACCAAGGCTTAAGCCATTATAGACGCAGCCCGTTAATTAGAGCTGCCGAGAGGGAGCTCTAAGATACTGAGATTAGTGGTTTGCGGTTGAAACCATGACGACCGAGTCCCGACGGAGCACGCGTAAGCGTCGTACCTACAGACTAAGCCTAACGTAACCATTGGGCATCAGTCCGCTTACTATGGATACGCTTCAGAACTCCCCTTGATTGCTCATAGCAAAAAAGTCCCAGCGACACTGAGGTAACTTGCTGGTAAAGACTCCATACGCCTGTAGCGCATGCATTTGTCGGCAAGCTTCCCTCCCACGGTCTATATTTCTGGTCAATCCCGCGAATACTGGTTTAATTTTTACGCTCAGAACACCGTGTGCGGTTACGCGATTACACCCGAAAATAATCCTACCAGACAGCCAAGAGACCGCCGGGCGAAAGCTACCTGGATGGACGCTTCAAAAGGGGCAGAGGCAGTTATGAACCTGTGCTTCCACACTAAAGTACAAGGGCTCTGGTCGGTCGGTATGACCTTACCCATCTTGACCTTGTTTAACACGATAGGTAGGGCCATGAAGGACCGGCGAGTGTGTCACCCTTGTAATTTTACGCCCTGGGGTCGGCAATCTACTCTTGCCTCCTGGCCGCCGCTTAAGGATAGGCCGGTATCGTGCAGTCTGAATATCTGCCGAACAAGGGCTTGCTGGGGGCCCTTCGGCTCTGCACATTGTATCCAGACAGCGGAAGACGATTACCCATCCATGTATGGTGCAATCGCTGCAAAGGATGTACCAAAGGGTCCAGCTGAAAATCTAACTCATTTCACTTGCAGTAAGATGGTGTCAGGCCCAATATCAATAAAGTCGCATGACACGTCGTCAGAAGCCGCAAGGTCTACAATGGTTCAACCCTGTAGTACTATTTGGGTGGCACTGCTTCCA"
    ))
